version: '3.9'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: app-php
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html:cached
    networks: [app]

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: app-node
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend:cached
    ports:
      - "3000:3000" # фронт: http://localhost:3000
    command: >
      sh -c "npm install --omit=dev && node js/server.js"
    networks: [app]

  nginx:
    image: nginx:1.25-alpine
    container_name: app-nginx
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./backend:/var/www/html:ro
    ports:
      - "8080:80"
    networks: [app]

networks:
  app:
